# satellites_db.py
SATELLITES = [
    {
        "mission_name": "Sentinel-1A",
        "constellation": "Sentinel-1",
        "instrument_name": "C-SAR",
        "operator": "ESA (Copernicus)",
        "sensor_type": "SAR",
        "spectral_band": "C-band",
        "spatial_resolution_m": "5–40",
        "revisit": "6–12 日",
        "coverage": "Global",
        "data_access": "無償",
        "official_url": "https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-1",
        "status": "Active",
        "launch_year": "2014",
        "notes": "Flood/InSAR 等"
    },
    {
        "mission_name": "Sentinel-2A",
        "constellation": "Sentinel-2",
        "instrument_name": "MSI",
        "operator": "ESA (Copernicus)",
        "sensor_type": "Optical-MS",
        "spectral_band": "VNIR + SWIR",
        "spatial_resolution_m": "10/20/60",
        "revisit": "5 日",
        "coverage": "Global (Land)",
        "data_access": "無償",
        "official_url": "https://sentinels.copernicus.eu/web/sentinel/missions/sentinel-2",
        "status": "Active",
        "launch_year": "2015",
        "notes": "Vegetation, NDVI"
    },
    {
        "mission_name": "Landsat 8",
        "constellation": "Landsat",
        "instrument_name": "OLI",
        "operator": "USGS / NASA",
        "sensor_type": "Optical-MS",
        "spectral_band": "VNIR + SWIR",
        "spatial_resolution_m": "15/30",
        "revisit": "16 日",
        "coverage": "Global (land)",
        "data_access": "無償",
        "official_url": "https://www.usgs.gov/landsat-missions/landsat-8",
        "status": "Active",
        "launch_year": "2013",
        "notes": "LULC"
    },
    {
        "mission_name": "Landsat 8",
        "constellation": "Landsat",
        "instrument_name": "TIRS",
        "operator": "USGS / NASA",
        "sensor_type": "Thermal-IR",
        "spectral_band": "TIR",
        "spatial_resolution_m": "100 (30 resample)",
        "revisit": "16 日",
        "coverage": "Global (land)",
        "data_access": "無償",
        "official_url": "https://www.usgs.gov/landsat-missions/landsat-8",
        "status": "Active",
        "launch_year": "2013",
        "notes": "Temperature"
    },
    {
        "mission_name": "WorldView-3",
        "constellation": "WorldView",
        "instrument_name": "WV3 (Pan/MS/SWIR/CAVIS)",
        "operator": "Maxar",
        "sensor_type": "Optical-MS",
        "spectral_band": "Pan + VNIR + SWIR",
        "spatial_resolution_m": "0.31/1.24/3.7",
        "revisit": "< 1 日 (tasking)",
        "coverage": "Global (tasking)",
        "data_access": "有償 (商用)",
        "official_url": "https://www.maxar.com/satellites/worldview-3",
        "status": "Active",
        "launch_year": "2014",
        "notes": "VHR"
    },
    {
        "mission_name": "PlanetScope",
        "constellation": "PlanetScope",
        "instrument_name": "Dove MS",
        "operator": "Planet Labs",
        "sensor_type": "Optical-MS",
        "spectral_band": "VNIR (4–8 band)",
        "spatial_resolution_m": "約3",
        "revisit": "1 日 (constellation)",
        "coverage": "Global (land)",
        "data_access": "有償 (商用)",
        "official_url": "https://www.planet.com/products/planet-scope/",
        "status": "Active",
        "launch_year": "2016",
        "notes": "Agriculture"
    },
    # ...（必要に応じて残りも順次追記）
]
